### ISSUE TITLE
lsmeans is going away

### ISSUE THREAD

**Issue by rvlenth** [CDEager/standardize#1]
Hello,

I’m writing because your R package **standardize** suggests the **lsmeans** package. For almost a year, the new package **emmeans** has been available, and I am planning to ask the CRAN team to deprecate it in the next few months. It is quite easy to make the transition to **emmeans**. There is a vignette providing some tips for how to do this at https://cran.r-project.org/web/packages/emmeans/vignettes/transition-from-lsmeans.html, and there is even a script for converting old R sources, vignettes, and workspaces.

Please let me know if you have any questions. I will keep in touch on this matter as is necessary.

Sincerely,

Russ Lenth

**Comment by jvcasillas** [comment]
Hey Chris @CDEager, 
I love this package and just noticed this issue. Do you have any plans to continue developing this? If not, I'm interested in forking to update for emmeans and then possibly resubmit to cran. Just curious about your plans.

**Comment by rvlenth** [comment]
The **emmeans** package is still actively going and being developed further. I switched to "estimated marginal means" because what was being added to **lsmeans** was going far beyond least squares.

Meanwhile, **lsmeans** had a user base and is even used in some textbooks. So it is impractical to deprecate it. Instead, I reworked it so it is a front-end for **emmeans** with some patches that make it possible for old objects saved from past sessions, and old lsmeans code, to still work. So **lsmeans** is not going anywhere and there is no urgency to making any changes.

However, I do recommend (at your convenience) changing your Suggests entry to replace **lsmeans** with **emmeans**, as it has a number of useful vignettes. Moreover, the `lsmeans()` function itself is actually in **emmeans**.

**Comment by CDEager** [comment]
Hey @jvcasillas, I will look through the package this week and figure out what needs to be updated.  I wrote the package I think almost 4 years ago now as part of my dissertation, so it will take a me a bit to refresh myself on how I wrote it originally.  I'll make a patch that switches to **emmeans** instead of **lsmeans**, and then take another look to see if the package can be improved more generally in a later release.

**Comment by jvcasillas** [comment]
> Hey @jvcasillas, I will look through the package this week and figure out what needs to be updated. I wrote the package I think almost 4 years ago now as part of my dissertation, so it will take a me a bit to refresh myself on how I wrote it originally. I'll make a patch that switches to **emmeans** instead of **lsmeans**, and then take another look to see if the package can be improved more generally in a later release.

Great to hear! Let me know if I can help in any way, as I know you've moved on to other things. Hope you are doing well!

**Comment by CDEager** [comment]
This issue has been fixed here: eefa59228af20d1b4debf5d14928b0cda14c4ac4

I will release v0.2.2 with this fix to CRAN tomorrow.
